version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: reviz_db
      POSTGRES_USER: reviz_user
      POSTGRES_PASSWORD: reviz_pwd
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
